# Numpy

In [1]:
import numpy as np 

x = np.array([5, 2, 5])
type(x)

numpy.ndarray

In [3]:
list1 = [8,0,2]
y = np.array(list1)
print(y)

[8 0 2]


array([8, 0, 2])

In [4]:
x.size

3

In [5]:
x.shape

(3,)

In [9]:
# 2d array

arr_2d = np.array([[2,3,4],[5,6,7]])
print(arr_2d)

[[2 3 4]
 [5 6 7]]


In [11]:
arr_2d.size
arr_2d.shape

(2, 3)

In [12]:
arr_2d.ndim

2

## Indexing and Slicing

In [13]:
list1 = [2,5,3,7,8] # 1d or vector
print(list1[2])

3


In [19]:
list1 = [[2, 18, 4],[8, 6, 22]]
x = np.array(list1)
print(x)

print(x[:,1])
print(x.diagonal())


[[ 2 18  4]
 [ 8  6 22]]
[18  6]
[2 6]


In [34]:
list3 = [[2, 18, 4],[8, 6, 22], [4, 6, 7]]

y = np.array(list3)
print(y)

print(y[1, 2])

print(y[1:,1:])



[[ 2 18  4]
 [ 8  6 22]
 [ 4  6  7]]
22
[[ 6 22]
 [ 6  7]]


In [39]:
mean = np.mean(y)
print(mean)

8.555555555555555


In [40]:
median = np.median(y)
print(median)

6.0


## Broadcasting

In [47]:
arr1 = np.array([3,4,5,6])
arr2 = np.array([[4],[4], [30]])
arr4 = np.array([[[4],[4]]])

arr3 = arr1 + arr2
arr5 = arr4 + arr1

print(arr5)

[[[ 7  8  9 10]
  [ 7  8  9 10]]]


# Pandas

In [1]:
import pandas as pd